services:
  skin:
    image: ghcr.io/lakelink/blessing-skin-server
    restart: unless-stopped
    volumes:
      - ./data/skin/public:/var/www/html/public
      - ./data/skin/storage:/var/www/html/storage
      # - skin-public:/var/www/html/public
      # - skin-storage:/var/www/html/storage
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      # mysql/mariadb/pgsql 需要等待数据库启动完成
      # - db
      - redis

  # PostgreSQL 数据库服务
  # db:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: username
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: blessingskin
  #   volumes:
  #     - ./db:/var/lib/postgresql/data
  #     - /etc/localtime:/etc/localtime:ro

  # MariaDB 数据库服务
  # db:
  #   image: mariadb:10.6
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: blessingskin
  #     MYSQL_USER: username
  #     MYSQL_PASSWORD: secret
  #   volumes:
  #     - ./db:/var/lib/mysql 
  #     - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
      - /etc/localtime:/etc/localtime:ro

  caddy:
    image: caddy:2.11-alpine
    restart: unless-stopped
    volumes:
      - ./data/skin/public:/skin/public:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/localtime:/etc/localtime:ro
    # depends_on:
    #   skin:
    #     condition: service_healthy

  janus:
    # 手动启动 Janus 容器
    # profiles: ["janus"]
    # 使用对应数据库的 Janus 镜像
    image: ghcr.io/lakelink/janus:sqlite
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./data/skin/janus.env
        target: /app/.env
        bind:
          create_host_path: false
      - type: bind
        source: ./data/skin/storage/oauth-private.key
        target: /app/oauth-private.key
        read_only: true
        bind:
          create_host_path: false
      # sqlite 将数据库文件挂载到容器内（与 Blessing Skin 容器内路径相同）
      - type: bind
        source: ./data/skin/storage/database.db
        target: /app/database.db
        bind:
          create_host_path: false
    # depends_on:
      # mysql/mariadb/pgsql 需要等待数据库启动完成
      # db:
      #   condition: service_started
